from __future__ import annotations

TAGS: list[str] = [
    "angry",
    "audience laughter",
    "calm",
    "chuckle",
    "chuckling",
    "clearing throat",
    "confident",
    "crying",
    "curious",
    "delight",
    "disgusted",
    "echo",
    "embarrassed",
    "emphasis",
    "excited",
    "excited tone",
    "exhale",
    "gasping",
    "inhale",
    "interrupting",
    "laughing",
    "laughing tone",
    "loud",
    "low voice",
    "low volume",
    "moaning",
    "nervous",
    "panting",
    "pause",
    "relaxed",
    "sad",
    "sarcastic",
    "screaming",
    "shocked",
    "short pause",
    "shouting",
    "sigh",
    "singing",
    "sobbing",
    "surprised",
    "tsk",
    "volume down",
    "volume up",
    "whisper",
    "with strong accent",
    "yawning",
]
